name: 'Armbian/build'
author: 'Stefan Dej'
description: 'Build armbian images'
inputs:
  configfile:
    description: 'Config file name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Runner prepare
      uses: ./actions/runner-prepare

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: build-configs

    - name: Read configs
      id: config
      shell: bash
      run: |
        source ./build-configs/configs/config-default.conf
        source ./build-configs/configs/board-${{ inputs.configfile }}.conf
        
        echo "armbian_repository=${ARMBIAN_REPOSITORY}" >> $GITHUB_OUTPUT
        echo "armbian_branch=${ARMBIAN_BRANCH}" >> $GITHUB_OUTPUT

    - name: Checkout armbian Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: ${{ steps.config.outputs.armbian_repository }}
        ref: ${{ steps.config.outputs.armbian_branch }}
        path: build

    - name: Create config-default.conf
      shell: bash
      run: |
        mkdir -p ./build/userpatches
        cp ./build-configs/configs/config-default.conf ./build/userpatches/config-armbian.conf
        cat ./build-configs/configs/board-${{ inputs.configfile }}.conf >> ./build/userpatches/config-default.conf
        echo "::group::Output config-default.conf"
        cat ./build/userpatches/config-default.conf
        echo "::endgroup::"

    - name: Build Image
      shell: bash
      run: |
        cd ./build
        ./compile.sh armbian

    - name: Fix userrights
      shell: bash
      run: |
        WORKSPACE=$(echo ${{ github.workspace }})
        sudo chown -R $USER:$USER $WORKSPACE/build || true
        sudo chmod 0777 -R $WORKSPACE/build || true
        sudo df
